apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-deployment
  labels:
    app: apache-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-container
  template:
    metadata:
      labels:
        app: apache-container
    spec:
      containers:
        - name: apache-container
          image: jkwregistry.azurecr.io/azuredevopscontainerexample
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: container-loadbalancer
  labels:
    app: apache-container
spec:
  type: LoadBalancer
  selector:
    app: apache-container
  ports:
    - port: 80
      targetPort: 80